# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

`numpy.random.randn` generates samples from the normal distribution, while `numpy.random.rand` from uniform (in range [0,1)).  


In [2]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 2.85402286, -0.75772689,  0.37670619,  1.15438208, -0.51952414],
       [-0.44471125, -1.10551885, -0.14373727, -0.18801233,  0.92914851],
       [ 0.18086059,  0.11377439,  0.52654555,  0.56459933,  0.12205094]])

In the below case we want a random distribution

In [3]:
# Create a 1-dimensional NumPy array using np.array()
x = np.random.randn(3, 1)

# Create a 2-dimensional NumPy array using np.array()
y = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
z = np.random.rand(1, 2, 4)
x, y, z

(array([[-1.25014197],
        [-1.25170042],
        [ 0.75743036]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[0.66622248, 0.33491658, 0.10958387, 0.06470338],
         [0.8324948 , 0.82542851, 0.62234818, 0.8422804 ]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)


In [5]:
# Attributes of 2-dimensional array


In [6]:
# Attributes of 3-dimensional array
z.shape, type(z), z.dtype, z.size

((1, 2, 4), numpy.ndarray, dtype('float64'), 8)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(y)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
np.ones((10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10,
            endpoint=True) # by default True

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
x = np.random.randint(0, 10, size = (7, 2))
x.shape, x

((7, 2),
 array([[0, 4],
        [2, 8],
        [5, 1],
        [4, 7],
        [7, 1],
        [3, 4],
        [2, 3]]))

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3, 5)

array([[0.5765515 , 0.21991929, 0.44008299, 0.39419488, 0.54816086],
       [0.54676519, 0.49625481, 0.85444605, 0.99375115, 0.98131798],
       [0.36321093, 0.31390964, 0.80321027, 0.62395524, 0.21342925]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, size = (4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
x = np.random.randint(0, 10, size = (3, 7))
print(x)
# Find the unique numbers in the array you just created
np.unique(x)

[[8 0 9 2 6 3 8]
 [2 4 2 6 4 8 6]
 [1 3 8 1 9 8 9]]


array([0, 1, 2, 3, 4, 6, 8, 9])

In [15]:
# Find the 0'th index of the latest array you created
x[0]

array([8, 0, 9, 2, 6, 3, 8])

In [16]:
# Get the first 2 rows of latest array you created
x[0:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
x[:2, :2]

array([[8, 0],
       [2, 4]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
x = np.random.randint(0, 10, size = (3, 5))
y = np.ones((3, 5))

x, y

(array([[4, 1, 3, 6, 7],
        [2, 0, 3, 1, 7],
        [3, 1, 5, 5, 9]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [19]:
# Add the two arrays together
x + y

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [20]:
# Create another array of ones of shape (5, 3)
z = np.ones((5, 3))

In [21]:
# Try add the array of ones and the other most recent array together
x + z

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)
a = np.ones((3, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# Subtract the new array of ones from the other most recent array
x - a

array([[ 3.,  0.,  2.,  5.,  6.],
       [ 1., -1.,  2.,  0.,  6.],
       [ 2.,  0.,  4.,  4.,  8.]])

In [24]:
# Multiply the ones array with the latest array
a*x

array([[4., 1., 3., 6., 7.],
       [2., 0., 3., 1., 7.],
       [3., 1., 5., 5., 9.]])

In [25]:
# Take the latest array to the power of 2 using '**'
x**2 

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]], dtype=int32)

In [26]:
%%time
# Do the same thing with np.square()
np.power(x, 100) # np.square(x)

Wall time: 0 ns


array([[          0,           1,  -818408495,           0,  1027218017],
       [          0,           0,  -818408495,           1,  1027218017],
       [ -818408495,           1, -1971132175, -1971132175, -1426542431]],
      dtype=int32)

In [27]:
# Find the mean of the latest array using np.mean()
# Find the maximum of the latest array using np.max()
# Find the minimum of the latest array using np.min()
# Find the standard deviation of the latest array
np.std(x), np.std(x, axis = 1), np.std(x, axis = 0)
# Find the variance of the latest array

(2.5612496949731396,
 array([2.13541565, 2.41660919, 2.65329983]),
 array([0.81649658, 0.47140452, 0.94280904, 2.1602469 , 0.94280904]))

In [28]:
# Reshape the latest array to (3, 5, 1)
np.reshape(x, (3, 5, 1))

array([[[4],
        [1],
        [3],
        [6],
        [7]],

       [[2],
        [0],
        [3],
        [1],
        [7]],

       [[3],
        [1],
        [5],
        [5],
        [9]]])

In [29]:
# Transpose the latest array
x.T

array([[4, 2, 3],
       [1, 0, 1],
       [3, 3, 5],
       [6, 1, 5],
       [7, 7, 9]])

What does the transpose do?

In [30]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1 = np.random.randint(0, 10, size = (3, 3))
a2 = np.random.randint(0, 10, size = (3, 2))
a1, a2

(array([[3, 5, 1],
        [9, 1, 9],
        [3, 7, 6]]),
 array([[8, 7],
        [4, 1],
        [4, 7]]))

In [31]:
# Perform a dot product on the two newest arrays you created
a1.dot(a2) # a2.dot(a1), this will not work 

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [32]:
np.dot(a1, a2) # np.dot(a2, a1), this will not work

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [33]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
b1 = np.random.randint(0, 10, size = (4, 3))
b2 = np.random.randint(0, 10, size = (4, 3))
b1, b2

(array([[9, 8, 8],
        [0, 8, 6],
        [8, 7, 0],
        [7, 7, 2]]),
 array([[0, 7, 2],
        [2, 0, 4],
        [9, 6, 9],
        [8, 6, 8]]))

In [34]:
# Perform a dot product on the two newest arrays you created
np.dot(b1, b2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [35]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(b1, b2.T) # or np.dot(b2, b1.T)

array([[ 72,  50, 201, 184],
       [ 68,  24, 102,  96],
       [ 49,  16, 114, 106],
       [ 53,  22, 123, 114]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [36]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


What happens when you compare the arrays with `>`?

In [37]:
# Compare the two arrays with '>='
b1 >= b2

array([[ True,  True,  True],
       [False,  True,  True],
       [False,  True, False],
       [False,  True, False]])

In [38]:
# Find which elements of the first array are greater than 7
b1 > 7

array([[ True,  True,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False, False]])

In [39]:
# Sort one of the arrays you just created in ascending order
b1, np.sort(b1), np.sort(b1, axis = 0)


(array([[9, 8, 8],
        [0, 8, 6],
        [8, 7, 0],
        [7, 7, 2]]),
 array([[8, 8, 9],
        [0, 6, 8],
        [0, 7, 8],
        [2, 7, 7]]),
 array([[0, 7, 0],
        [7, 7, 2],
        [8, 8, 6],
        [9, 8, 8]]))

In [40]:
-np.sort(-b1) # reverse sort

array([[9, 8, 8],
       [8, 6, 0],
       [8, 7, 0],
       [7, 7, 2]])

In [41]:
# Sort the indexes of one of the arrays you just created
np.argsort(b1)

array([[1, 2, 0],
       [0, 2, 1],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [42]:
# Find the index with the maximum value in one of the arrays you've created
# Find the index with the minimum value in one of the arrays you've created
b1, np.argmax(b1), np.argmin(b1)

(array([[9, 8, 8],
        [0, 8, 6],
        [8, 7, 0],
        [7, 7, 2]]),
 0,
 3)

In [43]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(b1, axis = 1), np.argmin(b1, axis = 1)

(array([0, 1, 0, 0], dtype=int64), array([1, 0, 2, 2], dtype=int64))

In [44]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmax(b1, axis = 0), np.argmin(b1, axis = 0)

(array([0, 0, 0], dtype=int64), array([1, 2, 2], dtype=int64))

In [45]:
b1.sum(axis = 0)

array([24, 30, 16])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.