# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.random.randint(10, size = (5, 1))

# Create a 2-dimensional NumPy array using np.array()
a2 = np.random.randint(10, size = (5, 3))


# Create a 3-dimensional Numpy array using np.array()
a3 = np.random.randint(10, size = (5, 3, 3))


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
a1, a2, a3

(array([[1],
        [0],
        [8],
        [5],
        [2]]),
 array([[8, 2, 5],
        [9, 4, 9],
        [7, 6, 1],
        [3, 1, 4],
        [0, 3, 0]]),
 array([[[8, 1, 0],
         [4, 2, 9],
         [3, 8, 1]],
 
        [[5, 0, 3],
         [5, 6, 9],
         [6, 2, 8]],
 
        [[5, 9, 3],
         [8, 2, 2],
         [6, 2, 6]],
 
        [[1, 9, 3],
         [0, 8, 4],
         [0, 9, 3]],
 
        [[6, 5, 9],
         [3, 0, 9],
         [5, 1, 7]]]))

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(2, dtype('int32'), 5, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array


In [6]:
# Attributes of 3-dimensional array


In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df1 = pd.DataFrame(a2)
df1

0  1  2
0  8  2  5
1  9  4  9
2  7  6  1
3  3  1  4
4  0  3  0

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zero = np.zeros((7, 2, 3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.arange(0, 100, 3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(10, size = (7,2))
a5

array([[1, 6],
       [9, 6],
       [7, 0],
       [5, 6],
       [5, 6],
       [7, 1],
       [5, 2]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.random((3, 5))
a6

array([[0.57457554, 0.04553376, 0.322852  , 0.99915917, 0.97596359],
       [0.50986677, 0.03070879, 0.61635393, 0.31440597, 0.51476471],
       [0.91445821, 0.89505057, 0.14123204, 0.5127398 , 0.64780472]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a7 = np.random.random((4, 6))
a7

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a8 = np.random.randint(5, size = (10, 7))
a8

array([[2, 3, 3, 0, 2, 4, 2],
       [4, 0, 1, 3, 0, 3, 1],
       [1, 0, 1, 4, 1, 3, 3],
       [3, 3, 4, 2, 0, 3, 1],
       [3, 1, 1, 3, 4, 1, 1],
       [3, 1, 1, 3, 3, 0, 4],
       [4, 1, 4, 1, 0, 3, 3],
       [3, 4, 0, 4, 4, 0, 0],
       [0, 0, 3, 2, 2, 0, 2],
       [2, 0, 2, 4, 1, 1, 0]])

In [15]:
# Find the unique numbers in the array you just created
np.unique(a8, return_index = True, return_inverse  = True, return_counts = True)

(array([0, 1, 2, 3, 4]),
 array([3, 9, 0, 1, 5], dtype=int64),
 array([2, 3, 3, 0, 2, 4, 2, 4, 0, 1, 3, 0, 3, 1, 1, 0, 1, 4, 1, 3, 3, 3,
        3, 4, 2, 0, 3, 1, 3, 1, 1, 3, 4, 1, 1, 3, 1, 1, 3, 3, 0, 4, 4, 1,
        4, 1, 0, 3, 3, 3, 4, 0, 4, 4, 0, 0, 0, 0, 3, 2, 2, 0, 2, 2, 0, 2,
        4, 1, 1, 0], dtype=int64),
 array([15, 16,  9, 18, 12], dtype=int64))

In [16]:
# Find the 0'th index of the latest array you created
a8[0]

array([2, 3, 3, 0, 2, 4, 2])

In [17]:
# Get the first 2 rows of latest array you created
a8[:2]

array([[2, 3, 3, 0, 2, 4, 2],
       [4, 0, 1, 3, 0, 3, 1]])

In [18]:
# Get the first 2 values of the first 2 rows of the latest array
a8[:2, :2]

array([[2, 3],
       [4, 0]])

In [19]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a9 = np.random.randint(10, size = (3, 5))
a10 = np.ones((3, 5))

In [20]:
a9, a10

(array([[6, 8, 7, 1, 0],
        [6, 6, 7, 4, 2],
        [7, 5, 2, 0, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [21]:
# Add the two arrays together
a9 + a10

array([[7., 9., 8., 2., 1.],
       [7., 7., 8., 5., 3.],
       [8., 6., 3., 1., 3.]])

In [22]:
# Create another array of ones of shape (5, 3)
a11 = np.random.randint(10, size = (5, 3))
a11

array([[4, 2, 0],
       [4, 9, 6],
       [6, 8, 9],
       [9, 2, 6],
       [0, 3, 3]])

In [23]:
# Try add the array of ones and the other most recent array together
#can't do

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [24]:
# Create another array of ones of shape (3, 5)
a12 = np.random.randint(5, 10, size = (3, 5))

In [25]:
a12

array([[9, 9, 7, 9, 8],
       [9, 7, 7, 8, 6],
       [6, 9, 5, 9, 8]])

In [26]:
# Subtract the new array of ones from the other most recent array
a12 - a9

array([[ 3,  1,  0,  8,  8],
       [ 3,  1,  0,  4,  4],
       [-1,  4,  3,  9,  6]])

In [27]:
# Multiply the ones array with the latest array
a12 * a9

array([[54, 72, 49,  9,  0],
       [54, 42, 49, 32, 12],
       [42, 45, 10,  0, 16]])

In [28]:
# Take the latest array to the power of 2 using '**'
a12**2

array([[81, 81, 49, 81, 64],
       [81, 49, 49, 64, 36],
       [36, 81, 25, 81, 64]], dtype=int32)

In [29]:
# Do the same thing with np.square()
np.array(a12)

array([[9, 9, 7, 9, 8],
       [9, 7, 7, 8, 6],
       [6, 9, 5, 9, 8]])

In [30]:
# Find the mean of the latest array using np.mean()
np.mean(a12), np.max(a12), np.min(a12), np.std(a12)

(7.733333333333333, 9, 5, 1.2892719737209144)

In [31]:
# Find the maximum of the latest array using np.max()


In [32]:
# Find the minimum of the latest array using np.min()


In [33]:
# Find the standard deviation of the latest array


In [34]:
# Find the variance of the latest array


In [35]:
a12.shape 

(3, 5)

In [36]:
# Reshape the latest array to (3, 5, 1)
a12.reshape((3, 5, 1))

array([[[9],
        [9],
        [7],
        [9],
        [8]],

       [[9],
        [7],
        [7],
        [8],
        [6]],

       [[6],
        [9],
        [5],
        [9],
        [8]]])

In [37]:
# Transpose the latest array
a12.T

array([[9, 9, 6],
       [9, 7, 9],
       [7, 7, 5],
       [9, 8, 9],
       [8, 6, 8]])

What does the transpose do?

In [38]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
b1 = np.random.randint(10, size = (3, 3))
b2 = np.random.randint(10, size = (3, 2))

In [39]:
b1, b2

(array([[3, 9, 6],
        [8, 6, 0],
        [0, 8, 8]]),
 array([[3, 8],
        [2, 6],
        [5, 7]]))

In [40]:
# Perform a dot product on the two newest arrays you created
b1.dot(b2)

array([[ 57, 120],
       [ 36, 100],
       [ 56, 104]])

In [41]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
c1 = np.random.randint(10, size = (4, 3))
c2 = np.random.randint(10, size = (4, 3))

In [42]:
c1, c2

(array([[8, 4, 0],
        [2, 9, 7],
        [5, 7, 8],
        [3, 0, 0]]),
 array([[9, 3, 6],
        [1, 2, 0],
        [4, 0, 7],
        [0, 0, 1]]))

In [44]:
# Perform a dot product on the two newest arrays you created
#c1.dot(c2)

It doesn't work. How would you fix it?

In [45]:
c1.shape, c2.T.shape

((4, 3), (3, 4))

In [46]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
c1.dot(c2.T)

array([[ 84,  16,  32,   0],
       [ 87,  20,  57,   7],
       [114,  19,  76,   8],
       [ 27,   3,  12,   0]])

In [47]:
c2.dot(c1.T)

array([[ 84,  87, 114,  27],
       [ 16,  20,  19,   3],
       [ 32,  57,  76,  12],
       [  0,   7,   8,   0]])

In [48]:
np.dot(c1, c2.T)

array([[ 84,  16,  32,   0],
       [ 87,  20,  57,   7],
       [114,  19,  76,   8],
       [ 27,   3,  12,   0]])

In [49]:
np.dot(c1.T, c2)

array([[94, 28, 86],
       [73, 30, 73],
       [39, 14, 56]])

### Notice how the 2 above functions differ

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [50]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [51]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [52]:
# Compare the two arrays with '>='


In [53]:
# Find which elements of the first array are greater than 7
c1 > 7

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False]])

In [54]:
# Which parts of each array are equal? (try using '==')


In [55]:
# Sort one of the arrays you just created in ascending order
np.sort(c1)

array([[0, 4, 8],
       [2, 7, 9],
       [5, 7, 8],
       [0, 0, 3]])

In [56]:
# Sort the indexes of one of the arrays you just created
np.argsort(c1)

array([[2, 1, 0],
       [0, 2, 1],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [57]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(c1)

4

In [58]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(c1)

2

In [59]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(c1, axis = 1)

array([0, 1, 2, 0], dtype=int64)

In [60]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmax(c1, axis = 0)

array([0, 1, 2], dtype=int64)

In [61]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.6591823 ,  0.0039373 ,  0.4777541 , -0.25902864, -0.57470921],
       [-0.42149822,  0.33982096, -0.00738015,  0.76729684, -1.14979258],
       [-0.77533611,  0.77314086, -0.80182784,  1.38401572,  1.40520531]])

In [62]:
# Create an array with 10 evenly spaced numbers between 1 and 100
e1 = np.arange(1, 101, 11)
e1

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [63]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10, endpoint=False)

array([ 1. , 10.9, 20.8, 30.7, 40.6, 50.5, 60.4, 70.3, 80.2, 90.1])

In [64]:

np.linspace(1, 100, 10, endpoint=True)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.