# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [10]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                ['a', 'b', 'c'],
                [11, 12, 13]],
               [[4, 5, 6],
                ['x', 'y', 'z'],
                [19, 18, 17]]])

In [11]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[['1', '2', '3'],
         ['a', 'b', 'c'],
         ['11', '12', '13']],
 
        [['4', '5', '6'],
         ['x', 'y', 'z'],
         ['19', '18', '17']]], dtype='<U11'))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [12]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('<U11'), 18, numpy.ndarray)

In [13]:
# Attributes of 2-dimensional array


In [14]:
# Attributes of 3-dimensional array


In [18]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
df1 = pd.DataFrame(a2)
df1

0  1  2
0  1  2  3
1  4  5  6

In [20]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.arange(0, 100, 3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(0, 10, size = (7, 2))
a5

array([[9, 3],
       [7, 7],
       [4, 2],
       [1, 7],
       [0, 0],
       [9, 4],
       [3, 9]])

In [40]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.rand(3, 5)
a6

array([[0.46628397, 0.25455093, 0.71647468, 0.21863914, 0.0429269 ],
       [0.55172008, 0.35867346, 0.28950112, 0.96272547, 0.41564777],
       [0.89931141, 0.21731466, 0.31531999, 0.63482159, 0.00813653]])

In [41]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a7 = np.random.randint(0, 10, size = (4, 6))
a7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [43]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a8 = np.random.randint(1, 10, size = (3, 7))
a8

# Find the unique numbers in the array you just created
np.unique(a8)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a8

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]])

In [46]:
# Find the 0'th index of the latest array you created
a8[0]

array([7, 8, 3, 1, 4, 2, 8])

In [47]:
# Get the first 2 rows of latest array you created
a8[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [49]:
# Get the first 2 values of the first 2 rows of the latest array
a8[:2, :2]

array([[7, 8],
       [4, 2]])

In [50]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a9 = np.random.randint(10, size = (3, 5))
a10 = np.ones((3, 5))

In [56]:
# Add the two arrays together
a9 + 10

array([[11, 14, 17, 19, 18],
       [18, 10, 18, 16, 18],
       [17, 10, 17, 17, 12]])

In [57]:
# Create another array of ones of shape (5, 3)
a11 = np.random.randint(10, size = (5, 3))


In [52]:
# Try add the array of ones and the other most recent array together
#a9 + a11

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [54]:
# Create another array of ones of shape (3, 5)
a12 = np.random.randint(10, size = (3, 5))


In [55]:
# Subtract the new array of ones from the other most recent array
a9 - a12

array([[-5, -2,  0,  5,  6],
       [ 1, -5,  6,  6,  6],
       [ 3, -2,  7,  3, -7]])

In [58]:
# Multiply the ones array with the latest array
a9*a12

array([[ 6, 24, 49, 36, 16],
       [56,  0, 16,  0, 16],
       [28,  0,  0, 28, 18]])

In [60]:
# Take the latest array to the power of 2 using '**'
a9**2

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]], dtype=int32)

In [61]:
# Do the same thing with np.square()
np.square(a9)

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]], dtype=int32)

In [62]:
# Find the mean of the latest array using np.mean()
np.mean(a9)

5.466666666666667

In [63]:
# Find the maximum of the latest array using np.max()
np.max(a9)

9

In [28]:
# Find the minimum of the latest array using np.min()


In [64]:
# Find the standard deviation of the latest array
np.std(a9)

3.0739045022396008

In [65]:
# Find the variance of the latest array
np.var(a9)

9.448888888888888

In [66]:
# Reshape the latest array to (3, 5, 1)
a9.reshape((3, 5, 1))

array([[[1],
        [4],
        [7],
        [9],
        [8]],

       [[8],
        [0],
        [8],
        [6],
        [8]],

       [[7],
        [0],
        [7],
        [7],
        [2]]])

In [68]:
# Transpose the latest array
a9.T

array([[1, 8, 7],
       [4, 0, 0],
       [7, 8, 7],
       [9, 6, 7],
       [8, 8, 2]])

What does the transpose do?

In [69]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a13 = np.random.randint(10, size = (3, 3))
a14 = np.random.randint(10, size = (3, 2))

In [70]:
# Perform a dot product on the two newest arrays you created
np.dot(a13, a14)

array([[ 42,  24],
       [102, 104],
       [ 48, 112]])

In [82]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a15 = np.random.randint(10, size = (3, 3))
a16 = np.random.randint(10, size = (4, 3))

In [83]:
# Perform a dot product on the two newest arrays you created
np.dot(a15, a16)

ValueError: shapes (3,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [84]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a15, a16.T)

array([[17, 40,  4, 43],
       [ 4, 16,  8, 36],
       [ 7, 42,  0, 28]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [85]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [86]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [87]:
# Compare the two arrays with '>='


In [88]:
# Find which elements of the first array are greater than 7


In [89]:
# Which parts of each array are equal? (try using '==')


In [90]:
a15

array([[6, 1, 2],
       [0, 4, 0],
       [7, 0, 0]])

In [91]:
# Sort one of the arrays you just created in ascending order
np.sort(a15)


array([[1, 2, 6],
       [0, 0, 4],
       [0, 0, 7]])

In [93]:
# Sort the indexes of one of the arrays you just created
a15.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [96]:
# Find the index with the maximum value in one of the arrays you've created
a15.argmax()

In [97]:
# Find the index with the minimum value in one of the arrays you've created


8

In [98]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
a15.argmax(axis = 1)

array([2, 2, 2], dtype=int64)

In [99]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
a15.argmax(axis = 0)

array([0, 0, 2], dtype=int64)

In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.